#!/bin/bash

TARGET_DIR="C:\Users\USUARIO\Desktop\INICIO_TOOLOPTIMIZERCNC\DOCS_TREINAMENTO_RAG"

# Array de arquivos a copiar
files=(
  "CLAUDE.md"
  "docs/ROADMAP_SESSAO_ATUAL.md"
  ".interface-design/system.md"
  "package.json"
  "docs/specs/PRD_MASTER.md"
  "docs/specs/PRD_TOOLOPTIMIZER_CNC_MVP.md"
  "docs/specs/DECISOES_VALIDACAO_PRD.md"
  "docs/technical/srctypes.md"
  "src/types/index.ts"
  "src/admin/types/admin-types.ts"
  "docs/technical/ESPECIFICACAO_TECNICA_CONSOLIDADA.md"
  "docs/technical/DADOS_TECNICOS_KIENZLE_E_VC.md"
  "docs/technical/PRD_Velocidades_Corte_CNC.md"
  "docs/technical/CASOS_TESTE_REFERENCIA.md"
  "docs/technical/padronizacao-adotada.md"
  "docs/architecture/ADR-001-stack-tecnologica.md"
  "docs/architecture/ADR-002-estrategia-css.md"
  "docs/architecture/ADR-003-separacao-desktop-mobile.md"
  "docs/architecture/ADR-004-adocao-synkra-aios.md"
  "docs/architecture/ADR-005-electron-desktop-build.md"
  "docs/architecture/ADR-006-estrategia-versionamento.md"
  "docs/architecture/ADR-007-fenix-ai-engineering-system.md"
  "docs/ai/AI_SYSTEM.md"
  "docs/ai/protocols/ARCHITECTURE_PROTOCOL.md"
  "docs/ai/protocols/ARCH_SYNC_PROTOCOL.md"
  "docs/ai/protocols/DEBUG_PROTOCOL.md"
  "docs/ai/protocols/DECISION_PROTOCOL.md"
  "docs/ai/protocols/FEATURE_PROTOCOL.md"
  "docs/ai/protocols/HANDOFF_PROTOCOL.md"
  "docs/ai/protocols/REVIEW_PROTOCOL.md"
  "docs/ai/protocols/SESSION_PROTOCOL.md"
  "docs/ai/memory/ARCHITECTURE_LEARNINGS.md"
  "docs/ai/memory/COMMON_MISTAKES.md"
  "docs/ai/memory/ENGINEERING_MEMORY.md"
  "docs/ai/memory/PRODUCT_CONTEXT.md"
  "docs/design/UI_DESIGN_SPEC_FINAL.md"
  "docs/design/DASHBOARD.md"
  "docs/design/UI_BRANDING.md"
  "docs/architecture-map/LAYOUT_SPECS.md"
  "docs/PROXIMA_SESSAO.md"
  "docs/AIOS_INTEGRATION.md"
  "docs/architecture-map/README.md"
  "docs/architecture-map/WORKFLOWS.md"
  "docs/plans/BACKLOG_IMPLEMENTACAO.md"
  "docs/plans/Implementações ajustes Dashboard 30-03/AUDITORIA-E-PLANO-CORRECOES.md"
  "docs/plans/Implementações ajustes Dashboard 30-03/SPEC-VISOR-RESULTS-PANEL-v1.md"
  "docs/plans/Implementações ajustes Dashboard 30-03/CONTEXTO-PROXIMA-SESSAO.md"
  "docs/plans/PLAN_Redesign_Visual_Dashboard.md"
  "docs/plans/PLAN_Admin_Dashboard.md"
  "docs/plans/PLAN_Seguranca_Cibernetica.md"
  "docs/plans/TIMELINE_PENDENCIAS.md"
  "src/store/machining-store.ts"
  "src/store/history-store.ts"
  "src/store/index.ts"
  "src/admin/store/admin-store.ts"
  "src/admin/store/analytics-store.ts"
  "src/admin/store/usage-store.ts"
  "src/engine/index.ts"
  "src/engine/rpm.ts"
  "src/engine/feed.ts"
  "src/engine/power.ts"
  "src/engine/chip-thinning.ts"
  "src/engine/slider-bounds.ts"
  "src/engine/validators.ts"
  "src/engine/recommendations.ts"
  "vite.config.ts"
  "tsconfig.json"
  "wrangler.jsonc"
  "vitest.config.ts"
  "docs/ai/guides/GUIA-USO-CLAUDE-CODE.md"
  "docs/ai/guides/GUIA-USO-CLAUDE-DESKTOP.md"
  "docs/ai/commands/SESSION_COMMANDS.md"
  ".claude/agent.md"
  ".claude/fixplan.md"
)

count=0
for file in "${files[@]}"; do
  if [ -f "$file" ]; then
    mkdir -p "$TARGET_DIR/$(dirname "$file")"
    cp "$file" "$TARGET_DIR/$file"
    count=$((count + 1))
    echo "✓ [$count] Copiado: $file"
  else
    echo "✗ Não encontrado: $file"
  fi
done

echo ""
echo "Cópia concluída: $count arquivos transferidos para DOCS_TREINAMENTO_RAG"
